executable            = runjobs.sh
Proxy_path            = /afs/cern.ch/user/g/gkopp/x509up_u101898
arguments             = $(Proxy_path) /afs/cern.ch/work/g/gkopp/MWGR/CMSSW_11_2_2_patch1/src/HcalDigiAnalyzer-2018RAW/MyAnalyzer/python/ConfFile_2018D_cfg.py
output                = /afs/cern.ch/work/g/gkopp/MWGR/CMSSW_11_2_2_patch1/src/HcalDigiAnalyzer-2018RAW/MyAnalyzer/out/IsoBunch_2018D.out
error                 = /afs/cern.ch/work/g/gkopp/MWGR/CMSSW_11_2_2_patch1/src/HcalDigiAnalyzer-2018RAW/MyAnalyzer/error/IsoBunch_2018D.err
log                   = /afs/cern.ch/work/g/gkopp/MWGR/CMSSW_11_2_2_patch1/src/HcalDigiAnalyzer-2018RAW/MyAnalyzer/log/IsoBunch_2018D.log

+JobFlavour = "testmatch"
RequestCpus = 4

queue